name: chickenofmission
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^1.0.4
  uuid: ^3.0.6
  flutter_swipe_detector: ^2.0.0
  hive: ^2.1.1
  hive_flutter: ^1.1.0
  json_annotation: ^4.5.0
  auto_route: ^10.0.1
  get_it: ^8.0.3
  flutter_svg: ^2.0.17
  sizer: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/game/
    - assets/images/welcome/
    - assets/svg/
    - assets/svg/game/
    - assets/svg/welcome/

  fonts:
    - family: Araside
      fonts:
        - asset: fonts/Araside.ttf